version: 0.0
os: linux
files:
  - source: /
    destination: /dev/shm/jekyll-commiter
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 3600
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
